path_extract <- "dummy_data/extract/"
path_denominator <- "dummy_data/denominator/AcceptablePats.parquet"
path_define <- "dummy_data/define/"
path_hes_eligibility <- "dummy_data/linkage/Aurum_enhanced_eligibility_January_2022.dta"
path_linked_data <- "dummy_data/linked_data/"
path_linkage <- "dummy_data/linkage/"
path_codebrowsers <- "sensitive_input/CPRD Aurum 2023_03 Code browser/"
path_numunit <- "sensitive_input/NumUnit.txt"
path_common_dosages <- "sensitive_input/common_dosages.txt"
path_extract_ids <- "dummy_data/extract_ids.txt"